"""create_students_table

Revision ID: 67a7cec7fcf6
Revises: 
Create Date: 2026-04-03 02:07:34.366105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a7cec7fcf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False, comment='Фамилия'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Имя'),
    sa.Column('faculty', sa.String(length=100), nullable=False, comment='Факультет'),
    sa.Column('course', sa.String(length=200), nullable=False, comment='Курс'),
    sa.Column('grade', sa.Float(), nullable=False, comment='Оценка'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
